services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: work-depot
        ports:
            - "5432:5432"
        volumes:
            - ./docker/db:/var/lib/postgresql/data
        restart: always
